CREATE TABLE "SYSTEM_USERS" (
  "ID" integer PRIMARY KEY,
  "USERNAME" varchar(15),
  "EMAIL" varchar(30)
);

CREATE TABLE "ENC_TYPES" (
  "ID" integer PRIMARY KEY,
  "NAME" varchar(30) UNIQUE,
  "DESC" varchar(100)
);

CREATE TABLE "HO_USER_STATUS" (
  "ID" integer PRIMARY KEY,
  "NAME" varchar(30) UNIQUE,
  "DESC" varchar(100)
);

CREATE TABLE "HO_USER_ROLES" (
  "ID" integer PRIMARY KEY,
  "ROLE_NAME" VARCHAR(15) UNIQUE,
  "DESC" VARCHAR(100),
  "FIN_ENABLE" BOOLEAN
);

CREATE TABLE "HO_DEPARTMENTS" (
  "ID" integer PRIMARY KEY,
  "NAME" varchar(30) UNIQUE,
  "ADDED_ON" TIMESTAMP,
  "UPDATED_ON" TIMESTAMP
);

CREATE TABLE "HO_SUB_DEPARTMENTS" (
  "HO_DEP_ID" integer,
  "ID" integer PRIMARY KEY,
  "NAME" varchar(30) UNIQUE,
  "ADDED_ON" TIMESTAMP,
  "UPDATED_ON" TIMESTAMP
);

CREATE TABLE "HO_ADMIN_USERS" (
  "CREATED_BY" integer NOT NULL,
  "ID" integer PRIMARY KEY,
  "USERNAME" varchar(15),
  "EMPLOYEE_ID" integer NOT NULL,
  "EMAIL_ID" varchar(30) UNIQUE,
  "PHONE_NO" integer(10),
  "STATUS" integer,
  "ADDED_ON" TIMESTAMP,
  "UPDATED_ON" TIMESTAMP
);

CREATE TABLE "HO_ADMIN_AUTH" (
  "HO_ADMIN_ID" integer UNIQUE,
  "AUTH_CODE" varchar(100),
  "AUTH_SALT" varchar(100),
  "ENCTYPE" integer NOT NULL,
  "ADDED_ON" TIMESTAMP NOT NULL
);

CREATE TABLE "HO_ADMIN_AUTH_HISTORY" (
  "HO_ADMIN_ID" INT,
  "AUTH_CODE" varchar(100),
  "AUTH_SALT" varchar(100),
  "ENCTYPE" integer NOT NULL,
  "ADDED_ON" TIMESTAMP NOT NULL
);

CREATE TABLE "HO_ADMIN_LOGIN_HISTORY" (
  "HO_ADMIN_ID" INT NOT NULL,
  "LOGIN_TIME" TIMESTAMP NOT NULL,
  "LOGOUTTIME" TIMESTAMP,
  "IPADDRESS" integer,
  "DESC" VARCHAR
);

CREATE TABLE "HO_DEP_HEAD_USERS" (
  "CREATED_BY" integer,
  "HO_DEP_ID" integer,
  "EMAIL_ID" varchar(30) UNIQUE,
  "ID" integer UNIQUE,
  "NAME" varchar(30),
  "EMPLOYEE_ID" integer NOT NULL,
  "PHONE_NO" integer(10),
  "STATUS" integer,
  "ADDED_ON" TIMESTAMP NOT NULL,
  "UPDATED_ON" TIMESTAMP,
  PRIMARY KEY ("HO_DEP_ID", "EMAIL_ID")
);

CREATE TABLE "HO_DEP_HEAD_AUTH" (
  "HO_DEP_HEAD_ID" integer UNIQUE,
  "AUTH_CODE" varchar(100),
  "AUTH_SALT" varchar(100),
  "ENCTYPE" integer NOT NULL,
  "ADDED_ON" TIMESTAMP NOT NULL
);

CREATE TABLE "HO_DEP_HEAD_AUTH_HISTORY" (
  "HO_DEP_HEAD_ID" INT,
  "AUTH_CODE" varchar(100),
  "AUTH_SALT" varchar(100),
  "ENCTYPE" integer NOT NULL,
  "ADDED_ON" TIMESTAMP NOT NULL
);

CREATE TABLE "HO_DEP_HEAD_USERS_LOGIN_HISTORY" (
  "HO_DEP_HEAD_ID" INT,
  "LOGIN_TIME" TIMESTAMP NOT NULL,
  "LOGOUTTIME" TIMESTAMP,
  "IPADDRESS" integer,
  "DESC" VARCHAR
);

CREATE TABLE "HO_SUB_DEP_HEAD_USERS" (
  "CREATED_BY" integer,
  "HO_SUB_DEP_ID" integer,
  "EMAIL_ID" varchar(30) UNIQUE,
  "ID" integer,
  "NAME" varchar(30),
  "EMPLOYEE_ID" integer NOT NULL,
  "PHONE_NO" integer(10),
  "STATUS" integer,
  "ADDED_ON" TIMESTAMP NOT NULL,
  "UPDATED_ON" TIMESTAMP,
  PRIMARY KEY ("HO_SUB_DEP_ID", "EMAIL_ID", "ID")
);

CREATE TABLE "HO_SUB_DEP_HEAD_AUTH" (
  "HO_SUB_DEP_HEAD_ID" integer UNIQUE,
  "AUTH_CODE" varchar(100),
  "AUTH_SALT" varchar(100),
  "ENCTYPE" integer NOT NULL,
  "ADDED_ON" TIMESTAMP NOT NULL
);

CREATE TABLE "HO_SUB_DEP_HEAD_AUTH_HISTORY" (
  "HO_SUB_DEP_HEAD_ID" INT,
  "AUTH_CODE" varchar(100),
  "AUTH_SALT" varchar(100),
  "ENCTYPE" integer NOT NULL,
  "ADDED_ON" TIMESTAMP NOT NULL
);

CREATE TABLE "HO_SUB_DEP_HEAD_LOGIN_HISTORY" (
  "HO_SUB_DEP_HEAD_ID" INT,
  "LOGIN_TIME" TIMESTAMP NOT NULL,
  "LOGOUTTIME" TIMESTAMP,
  "IPADDRESS" integer,
  "DESC" VARCHAR
);

CREATE TABLE "HO_SUB_DEP_USERS" (
  "CREATED_BY" integer,
  "HO_SUBDEP_ID" integer,
  "ROLE_ID" integer,
  "EMAIL_ID" varchar(30) UNIQUE,
  "ID" integer,
  "NAME" varchar(30),
  "EMPLOYEE_ID" integer NOT NULL,
  "PHONE_NO" integer(10),
  "STATUS" integer,
  "ADDED_ON" TIMESTAMP NOT NULL,
  "UPDATED_ON" TIMESTAMP,
  PRIMARY KEY ("HO_SUBDEP_ID", "ROLE_ID", "EMAIL_ID", "ID")
);

CREATE TABLE "HO_SUB_DEP_USERS_AUTH" (
  "HO_SUB_DEP_USER_ID" integer UNIQUE,
  "AUTH_CODE" varchar(100),
  "AUTH_SALT" varchar(100),
  "ENCTYPE" integer NOT NULL,
  "ADDED_ON" TIMESTAMP NOT NULL
);

CREATE TABLE "HO_SUB_DEP_USERS_AUTH_HISTORY" (
  "HO_SUB_DEP_USER_ID" INT,
  "AUTH_CODE" varchar(100),
  "AUTH_SALT" varchar(100),
  "ENCTYPE" integer NOT NULL,
  "ADDED_ON" TIMESTAMP NOT NULL
);

CREATE TABLE "HO_SUB_DEP_USERS_LOGIN_HISTORY" (
  "HO_SUB_DEP_USER_ID" INT,
  "LOGIN_TIME" TIMESTAMP NOT NULL,
  "LOGOUTTIME" TIMESTAMP,
  "IPADDRESS" integer,
  "DESC" VARCHAR
);

COMMENT ON TABLE "HO_SUB_DEP_HEAD_USERS" IS 'We need only the Sub Department id as Department id we can get from Sub-department table';

COMMENT ON TABLE "HO_SUB_DEP_USERS" IS 'Use this for Supervisors,Executives and General Users only';

ALTER TABLE "HO_SUB_DEPARTMENTS" ADD FOREIGN KEY ("HO_DEP_ID") REFERENCES "HO_DEPARTMENTS" ("ID");

ALTER TABLE "HO_ADMIN_USERS" ADD FOREIGN KEY ("CREATED_BY") REFERENCES "SYSTEM_USERS" ("ID");

ALTER TABLE "HO_ADMIN_USERS" ADD FOREIGN KEY ("STATUS") REFERENCES "HO_USER_STATUS" ("ID");

ALTER TABLE "HO_ADMIN_AUTH" ADD FOREIGN KEY ("HO_ADMIN_ID") REFERENCES "HO_ADMIN_USERS" ("ID");

ALTER TABLE "HO_ADMIN_AUTH" ADD FOREIGN KEY ("ENCTYPE") REFERENCES "ENC_TYPES" ("ID");

ALTER TABLE "HO_ADMIN_AUTH_HISTORY" ADD FOREIGN KEY ("HO_ADMIN_ID") REFERENCES "HO_ADMIN_USERS" ("ID");

ALTER TABLE "HO_ADMIN_AUTH_HISTORY" ADD FOREIGN KEY ("ENCTYPE") REFERENCES "ENC_TYPES" ("ID");

ALTER TABLE "HO_ADMIN_LOGIN_HISTORY" ADD FOREIGN KEY ("HO_ADMIN_ID") REFERENCES "HO_ADMIN_USERS" ("ID");

ALTER TABLE "HO_DEP_HEAD_USERS" ADD FOREIGN KEY ("CREATED_BY") REFERENCES "HO_ADMIN_USERS" ("ID");

ALTER TABLE "HO_DEP_HEAD_USERS" ADD FOREIGN KEY ("HO_DEP_ID") REFERENCES "HO_DEPARTMENTS" ("ID");

ALTER TABLE "HO_DEP_HEAD_USERS" ADD FOREIGN KEY ("STATUS") REFERENCES "HO_USER_STATUS" ("ID");

ALTER TABLE "HO_DEP_HEAD_AUTH" ADD FOREIGN KEY ("HO_DEP_HEAD_ID") REFERENCES "HO_DEP_HEAD_USERS" ("ID");

ALTER TABLE "HO_DEP_HEAD_AUTH" ADD FOREIGN KEY ("ENCTYPE") REFERENCES "ENC_TYPES" ("ID");

ALTER TABLE "HO_DEP_HEAD_AUTH_HISTORY" ADD FOREIGN KEY ("HO_DEP_HEAD_ID") REFERENCES "HO_DEP_HEAD_USERS" ("ID");

ALTER TABLE "HO_DEP_HEAD_AUTH_HISTORY" ADD FOREIGN KEY ("ENCTYPE") REFERENCES "ENC_TYPES" ("ID");

ALTER TABLE "HO_DEP_HEAD_USERS_LOGIN_HISTORY" ADD FOREIGN KEY ("HO_DEP_HEAD_ID") REFERENCES "HO_DEP_HEAD_USERS" ("ID");

ALTER TABLE "HO_SUB_DEP_HEAD_USERS" ADD FOREIGN KEY ("CREATED_BY") REFERENCES "HO_DEP_HEAD_USERS" ("ID");

ALTER TABLE "HO_SUB_DEP_HEAD_USERS" ADD FOREIGN KEY ("HO_SUB_DEP_ID") REFERENCES "HO_SUB_DEPARTMENTS" ("ID");

ALTER TABLE "HO_SUB_DEP_HEAD_USERS" ADD FOREIGN KEY ("STATUS") REFERENCES "HO_USER_STATUS" ("ID");

ALTER TABLE "HO_SUB_DEP_HEAD_AUTH" ADD FOREIGN KEY ("HO_SUB_DEP_HEAD_ID") REFERENCES "HO_SUB_DEP_HEAD_USERS" ("ID");

ALTER TABLE "HO_SUB_DEP_HEAD_AUTH" ADD FOREIGN KEY ("ENCTYPE") REFERENCES "ENC_TYPES" ("ID");

ALTER TABLE "HO_SUB_DEP_HEAD_AUTH_HISTORY" ADD FOREIGN KEY ("HO_SUB_DEP_HEAD_ID") REFERENCES "HO_SUB_DEP_HEAD_USERS" ("ID");

ALTER TABLE "HO_SUB_DEP_HEAD_AUTH_HISTORY" ADD FOREIGN KEY ("ENCTYPE") REFERENCES "ENC_TYPES" ("ID");

ALTER TABLE "HO_SUB_DEP_HEAD_LOGIN_HISTORY" ADD FOREIGN KEY ("HO_SUB_DEP_HEAD_ID") REFERENCES "HO_SUB_DEP_HEAD_USERS" ("ID");

ALTER TABLE "HO_SUB_DEP_USERS" ADD FOREIGN KEY ("CREATED_BY") REFERENCES "HO_SUB_DEP_HEAD_USERS" ("ID");

ALTER TABLE "HO_SUB_DEP_USERS" ADD FOREIGN KEY ("HO_SUBDEP_ID") REFERENCES "HO_SUB_DEPARTMENTS" ("ID");

ALTER TABLE "HO_SUB_DEP_USERS" ADD FOREIGN KEY ("ROLE_ID") REFERENCES "HO_USER_ROLES" ("ID");

ALTER TABLE "HO_SUB_DEP_USERS" ADD FOREIGN KEY ("STATUS") REFERENCES "HO_USER_STATUS" ("ID");

ALTER TABLE "HO_SUB_DEP_USERS_AUTH" ADD FOREIGN KEY ("HO_SUB_DEP_USER_ID") REFERENCES "HO_SUB_DEP_USERS" ("ID");

ALTER TABLE "HO_SUB_DEP_USERS_AUTH" ADD FOREIGN KEY ("ENCTYPE") REFERENCES "ENC_TYPES" ("ID");

ALTER TABLE "HO_SUB_DEP_USERS_AUTH_HISTORY" ADD FOREIGN KEY ("HO_SUB_DEP_USER_ID") REFERENCES "HO_SUB_DEP_USERS" ("ID");

ALTER TABLE "HO_SUB_DEP_USERS_AUTH_HISTORY" ADD FOREIGN KEY ("ENCTYPE") REFERENCES "ENC_TYPES" ("ID");

ALTER TABLE "HO_SUB_DEP_USERS_LOGIN_HISTORY" ADD FOREIGN KEY ("HO_SUB_DEP_USER_ID") REFERENCES "HO_SUB_DEP_USERS" ("ID");

ALTER TABLE "HO_DEP_HEAD_USERS_LOGIN_HISTORY" ADD FOREIGN KEY ("IPADDRESS") REFERENCES "HO_DEP_HEAD_USERS_LOGIN_HISTORY" ("DESC");
