CREATE TYPE DOC_REVIEW_STATUS AS ENUM (
  'PENDING',
  'COMPLETED'
);
CREATE TABLE USER_DOC_REVIEW_REQUEST (
  ID bigint PRIMARY KEY,
  UDOC_ID bigint,
  REQUESTER_ID integer NOT NULL,
  REVIEWER_ID integer NOT NULL,
  REQUESTED_ON TIMESTAMP NOT NULL DEFAULT NOW(),
  REQUEST_EXPIRES_ON TIMESTAMP NOT NULL DEFAULT NOW()+ interval '1 day',
  REVIEW_STATUS DOC_REVIEW_STATUS NOT NULL,
  UPDATED_ON TIMESTAMP,
  UNIQUE (UDOC_ID,REQUESTER_ID,REVIEWER_ID)
);

CREATE TABLE USER_DOC_REVIEW_COMMENTS (
  ID bigint PRIMARY KEY,
  REVIEW_REQ_ID bigint NOT NULL,
  DOC_PAGE_ID integer,
  DOC_PAGE_LINE integer,
  COMMENT_TEXT varchar(300) NOT NULL,
  COMMENT_ADDED_ON TIMESTAMP DEFAULT NOW(),
  COMMENTS_BY integer
);
COMMENT ON COLUMN USER_DOC_REVIEW_REQUEST.REQUESTER_ID IS 'Review Requested by ';

COMMENT ON COLUMN USER_DOC_REVIEW_REQUEST.REVIEWER_ID IS 'To Get Review of the document';

COMMENT ON COLUMN USER_DOC_REVIEW_REQUEST.REQUEST_EXPIRES_ON IS 'Request Expiry Date should be defined and provide here';

ALTER TABLE USER_DOC_REVIEW_REQUEST ADD FOREIGN KEY (UDOC_ID) REFERENCES USER_DOCUMENT (ID);

ALTER TABLE USER_DOC_REVIEW_REQUEST ADD FOREIGN KEY (REQUESTER_ID) REFERENCES USERS (UID);

ALTER TABLE USER_DOC_REVIEW_REQUEST ADD FOREIGN KEY (REVIEWER_ID) REFERENCES USERS (UID);

ALTER TABLE USER_DOC_REVIEW_COMMENTS ADD FOREIGN KEY (REVIEW_REQ_ID) REFERENCES USER_DOC_REVIEW_REQUEST (ID);

ALTER TABLE USER_DOC_REVIEW_COMMENTS ADD FOREIGN KEY (COMMENTS_BY) REFERENCES USERS (UID);



