CREATE TYPE "USER_TYPES" AS ENUM (
  'INDIVIDUAL_USER',
  'CORPORATE_USER',
  'BUSINESS_USER'
);

CREATE TYPE "SUB_CORP_PLAN_TYPES" AS ENUM (
  'FREEMIUM',
  'BRONZE',
  'SILVER',
  'GOLD'
);

CREATE TYPE "SUB_BA_PLAN_TYPES" AS ENUM (
  'FREEMIUM',
  'BASIC',
  'EXECUTIVE',
  'ADVANCED'
);

CREATE TYPE "SUB_TENURE_TYPES" AS ENUM (
  'MONTHLY',
  'QUARTERLY',
  'HALFYEARLY',
  'YEARLY'
);

CREATE TYPE "SUB_PLAN_STATUS" AS ENUM (
  'ACTIVE',
  'INACTIVE'
);

CREATE TABLE "SYSTEM_USERS" (
  "ID" integer PRIMARY KEY,
  "USERNAME" varchar(15),
  "EMAIL" varchar(30)
);

CREATE TABLE "HO_ADMIN_USERS" (
  "CREATED_BY" integer NOT NULL,
  "EMAIL_ID" varchar(30) UNIQUE NOT NULL,
  "ID" integer PRIMARY KEY,
  "USERNAME" varchar(15),
  "EMPLOYEE_ID" integer NOT NULL,
  "PHONE_NO" integer(10),
  "STATUS" integer,
  "ADDED_ON" TIMESTAMP NOT NULL DEFAULT (now()),
  "UPDATED_ON" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "SUBSCRIPTIONS_PLANS_CORP" (
  "ID" integer PRIMARY KEY,
  "SUB_PLAN_TYPE" SUB_CORP_PLAN_TYPES NOT NULL DEFAULT 'FREEMIUM',
  "SUB_TENURE_TYPE" SUB_TENURE_TYPES DEFAULT 'MONTHLY',
  "SUB_TENURE_VALUE" integer NOT NULL,
  "price" integer NOT NULL,
  "allowed_doc_count" integer NOT NULL,
  "SUB_PLAN_STATUS" SUB_PLAN_STATUS DEFAULT 'ACTIVE',
  "DESC" varchar(30),
  "ADDED_ON" TIMESTAMP NOT NULL DEFAULT (now()),
  "UPDATED_ON" TIMESTAMP NOT NULL DEFAULT (now()),
  "CREATED_BY" integer
);

CREATE TABLE "SUBSCRIPTIONS_PLANS_CORP_VERSIONS" (
  "ID" integer PRIMARY KEY,
  "SUBS_PLAN_ID" integer NOT NULL,
  "VERSION" integer NOT NULL,
  "USER_TYPES_ID" USER_TYPES DEFAULT 'CORPORATE_USER',
  "SUB_PLAN_TYPE" SUB_CORP_PLAN_TYPES NOT NULL DEFAULT 'FREEMIUM',
  "SUB_TENURE_TYPE" SUB_TENURE_TYPES DEFAULT 'MONTHLY',
  "SUB_TENURE_VALUE" integer NOT NULL,
  "price" integer NOT NULL,
  "allowed_doc_count" integer NOT NULL,
  "SUB_PLAN_STATUS" SUB_PLAN_STATUS DEFAULT 'ACTIVE',
  "DESC" varchar(30),
  "ADDED_ON" TIMESTAMP NOT NULL DEFAULT (now()),
  "UPDATED_ON" TIMESTAMP NOT NULL DEFAULT (now()),
  "CREATED_BY" integer
);

CREATE TABLE "SUBSCRIPTIONS_PLANS_CORP_BENEFITS" (
  "SUBSCRIPTIONS_ID" integer,
  "BENE_SEQ" integer NOT NULL,
  "BENE_DESC" varchar[100] NOT NULL,
  "ADDED_ON" TIMESTAMP NOT NULL DEFAULT (now()),
  "UPDATED_ON" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "SUBSCRIPTIONS_PLANS_BA" (
  "ID" integer PRIMARY KEY,
  "SUB_PLAN_TYPE" SUB_BA_PLAN_TYPES NOT NULL DEFAULT 'FREEMIUM',
  "SUB_TENURE_TYPE" SUB_TENURE_TYPES DEFAULT 'MONTHLY',
  "SUB_TENURE_VALUE" integer NOT NULL,
  "price" integer NOT NULL,
  "allowed_doc_count" integer NOT NULL,
  "SUB_PLAN_STATUS" SUB_PLAN_STATUS DEFAULT 'ACTIVE',
  "DESC" varchar(30),
  "ADDED_ON" TIMESTAMP NOT NULL DEFAULT (now()),
  "UPDATED_ON" TIMESTAMP NOT NULL DEFAULT (now()),
  "CREATED_BY" integer
);

CREATE TABLE "SUBSCRIPTIONS_PLANS_BA_VERSIONS" (
  "ID" integer PRIMARY KEY,
  "SUBS_PLAN_ID" integer NOT NULL,
  "VERSION" integer NOT NULL,
  "USER_TYPES_ID" USER_TYPES DEFAULT 'CORPORATE_USER',
  "SUB_PLAN_TYPE" SUB_BA_PLAN_TYPES DEFAULT 'FREEMIUM',
  "SUB_TENURE_TYPE" SUB_TENURE_TYPES DEFAULT 'MONTHLY',
  "SUB_TENURE_VALUE" integer NOT NULL,
  "price" integer NOT NULL,
  "allowed_doc_count" integer NOT NULL,
  "SUB_PLAN_STATUS" SUB_PLAN_STATUS DEFAULT 'ACTIVE',
  "DESC" varchar(30),
  "ADDED_ON" TIMESTAMP NOT NULL DEFAULT (now()),
  "UPDATED_ON" TIMESTAMP NOT NULL DEFAULT (now()),
  "CREATED_BY" integer
);

CREATE TABLE "SUBSCRIPTIONS_PLANS_BA_BENEFITS" (
  "SUBSCRIPTIONS_ID" integer,
  "BENE_SEQ" integer NOT NULL,
  "BENE_DESC" varchar[100] NOT NULL,
  "ADDED_ON" TIMESTAMP NOT NULL DEFAULT (now()),
  "UPDATED_ON" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX "USERTYPE_SUBSCRIPTIONS" ON "SUBSCRIPTIONS_PLANS_CORP" ("SUB_PLAN_TYPE");

CREATE UNIQUE INDEX ON "SUBSCRIPTIONS_PLANS_CORP_VERSIONS" ("SUBS_PLAN_ID", "VERSION");

CREATE UNIQUE INDEX ON "SUBSCRIPTIONS_PLANS_CORP_VERSIONS" ("ID");

CREATE UNIQUE INDEX ON "SUBSCRIPTIONS_PLANS_CORP_BENEFITS" ("SUBSCRIPTIONS_ID", "BENE_SEQ");

CREATE UNIQUE INDEX "USERTYPE_SUBSCRIPTIONS" ON "SUBSCRIPTIONS_PLANS_BA" ("SUB_PLAN_TYPE");

CREATE UNIQUE INDEX ON "SUBSCRIPTIONS_PLANS_BA_VERSIONS" ("SUBS_PLAN_ID", "VERSION");

CREATE UNIQUE INDEX ON "SUBSCRIPTIONS_PLANS_BA_VERSIONS" ("ID");

CREATE UNIQUE INDEX ON "SUBSCRIPTIONS_PLANS_BA_BENEFITS" ("SUBSCRIPTIONS_ID", "BENE_SEQ");

COMMENT ON TABLE "HO_ADMIN_USERS" IS 'UPDATED_ON value should be added on update only';

COMMENT ON TABLE "SUBSCRIPTIONS_PLANS_CORP" IS 'UPDATED_ON value should be added on update only';

COMMENT ON TABLE "SUBSCRIPTIONS_PLANS_CORP_VERSIONS" IS 'UPDATED_ON value should be added on update only';

COMMENT ON TABLE "SUBSCRIPTIONS_PLANS_CORP_BENEFITS" IS 'UPDATED_ON value should be added on update only';

COMMENT ON TABLE "SUBSCRIPTIONS_PLANS_BA" IS 'UPDATED_ON value should be added on update only';

COMMENT ON TABLE "SUBSCRIPTIONS_PLANS_BA_VERSIONS" IS 'UPDATED_ON value should be added on update only';

COMMENT ON TABLE "SUBSCRIPTIONS_PLANS_BA_BENEFITS" IS 'UPDATED_ON value should be added on update only';

ALTER TABLE "HO_ADMIN_USERS" ADD FOREIGN KEY ("CREATED_BY") REFERENCES "SYSTEM_USERS" ("ID");

ALTER TABLE "SUBSCRIPTIONS_PLANS_CORP" ADD FOREIGN KEY ("CREATED_BY") REFERENCES "HO_ADMIN_USERS" ("ID");

ALTER TABLE "SUBSCRIPTIONS_PLANS_CORP_VERSIONS" ADD FOREIGN KEY ("SUBS_PLAN_ID") REFERENCES "SUBSCRIPTIONS_PLANS_CORP" ("ID");

ALTER TABLE "SUBSCRIPTIONS_PLANS_CORP_VERSIONS" ADD FOREIGN KEY ("CREATED_BY") REFERENCES "HO_ADMIN_USERS" ("ID");

ALTER TABLE "SUBSCRIPTIONS_PLANS_CORP_BENEFITS" ADD FOREIGN KEY ("SUBSCRIPTIONS_ID") REFERENCES "SUBSCRIPTIONS_PLANS_CORP" ("ID");

ALTER TABLE "SUBSCRIPTIONS_PLANS_BA" ADD FOREIGN KEY ("CREATED_BY") REFERENCES "HO_ADMIN_USERS" ("ID");

ALTER TABLE "SUBSCRIPTIONS_PLANS_BA_VERSIONS" ADD FOREIGN KEY ("SUBS_PLAN_ID") REFERENCES "SUBSCRIPTIONS_PLANS_BA" ("ID");

ALTER TABLE "SUBSCRIPTIONS_PLANS_BA_VERSIONS" ADD FOREIGN KEY ("CREATED_BY") REFERENCES "HO_ADMIN_USERS" ("ID");

ALTER TABLE "SUBSCRIPTIONS_PLANS_BA_BENEFITS" ADD FOREIGN KEY ("SUBSCRIPTIONS_ID") REFERENCES "SUBSCRIPTIONS_PLANS_BA" ("ID");
