CREATE TABLE "SYSTEM_USERS" (
  "ID" integer PRIMARY KEY,
  "USERNAME" varchar(15),
  "EMAIL" varchar(30)
);

CREATE TABLE "HO_ADMIN_USERS" (
  "CREATED_BY" integer,
  "EMAIL_ID" varchar(30) UNIQUE NOT NULL,
  "ID" integer PRIMARY KEY,
  "USERNAME" varchar(15),
  "EMPLOYEE_ID" integer NOT NULL,
  "PHONE_NO" integer(10),
  "STATUS" integer,
  "ADDED_ON" TIMESTAMP NOT NULL,
  "UPDATED_ON" TIMESTAMP
);

CREATE TABLE "STATE" (
  "ID" integer PRIMARY KEY,
  "code" integer UNIQUE NOT NULL,
  "name" varchar(15) UNIQUE NOT NULL,
  "DESC" varchar(30)
);

CREATE TABLE "CITY" (
  "ID" integer PRIMARY KEY,
  "STATE_ID" integer,
  "code" integer UNIQUE NOT NULL,
  "name" varchar(15) UNIQUE NOT NULL,
  "DESC" varchar(30)
);

CREATE TABLE "ENC_TYPES" (
  "ID" integer PRIMARY KEY,
  "NAME" varchar(30) UNIQUE,
  "DESC" varchar(100),
  "ADDED_ON" TIMESTAMP NOT NULL
);

CREATE TABLE "SO_USER_STATUS" (
  "ID" integer PRIMARY KEY,
  "NAME" varchar(30) UNIQUE,
  "DESC" varchar(100)
);

CREATE TABLE "SO_DEPARTMENTS" (
  "ID" integer PRIMARY KEY,
  "NAME" varchar(30) UNIQUE,
  "ADDED_ON" TIMESTAMP NOT NULL,
  "UPDATED_ON" TIMESTAMP
);

CREATE TABLE "SO_SUB_DEPARTMENTS" (
  "SO_DEP_ID" integer,
  "ID" integer PRIMARY KEY,
  "NAME" varchar(30) UNIQUE,
  "ADDED_ON" TIMESTAMP NOT NULL,
  "UPDATED_ON" TIMESTAMP
);

CREATE TABLE "SO_ADMIN_USERS" (
  "CREATED_BY" integer,
  "STATE_ID" integer,
  "CITY_ID" integer,
  "EMAIL_ID" varchar(30) UNIQUE NOT NULL,
  "ID" integer UNIQUE,
  "USERNAME" varchar(15),
  "EMPLOYEE_ID" integer NOT NULL,
  "PHONE_NO" integer(10),
  "ADDED_ON" TIMESTAMP NOT NULL,
  "UPDATED_ON" TIMESTAMP,
  "STATUS" integer,
  PRIMARY KEY ("STATE_ID", "CITY_ID", "EMAIL_ID")
);

CREATE TABLE "SO_ADMIN_AUTH_HISTORY" (
  "SO_ADMIN_ID" INT,
  "AUTH_CODE" varchar(100),
  "AUTH_SALT" varchar(100),
  "ENCTYPE" integer NOT NULL,
  "ADDED_ON" TIMESTAMP NOT NULL
);

CREATE TABLE "SO_ADMIN_LOGIN_HISTORY" (
  "SO_ADMIN_ID" INT NOT NULL,
  "LOGIN_TIME" TIMESTAMP NOT NULL,
  "LOGOUTTIME" TIMESTAMP,
  "IPADDRESS" integer,
  "DESC" VARCHAR
);

CREATE TABLE "SO_ADMIN_AUTH" (
  "SO_ADMIN_ID" integer UNIQUE,
  "AUTH_CODE" varchar(100),
  "AUTH_SALT" varchar(100),
  "ENCTYPE" integer NOT NULL,
  "ADDED_ON" TIMESTAMP NOT NULL
);

CREATE TABLE "SO_DEP_HEAD_USERS" (
  "CREATED_BY" integer,
  "SO_DEP_ID" integer,
  "STATE_ID" integer,
  "CITY_ID" integer,
  "EMAIL_ID" varchar(30) UNIQUE,
  "ID" integer UNIQUE,
  "NAME" varchar(30),
  "EMPLOYEE_ID" integer NOT NULL,
  "PHONE_NO" integer(10),
  "ADDED_ON" TIMESTAMP NOT NULL,
  "UPDATED_ON" TIMESTAMP,
  "STATUS" integer,
  PRIMARY KEY ("SO_DEP_ID", "STATE_ID", "CITY_ID", "EMAIL_ID")
);

CREATE TABLE "SO_DEP_HEAD_AUTH_HISTORY" (
  "SO_DEP_HEAD_ID" INT,
  "AUTH_CODE" varchar(100),
  "AUTH_SALT" varchar(100),
  "ENCTYPE" integer NOT NULL,
  "ADDED_ON" TIMESTAMP NOT NULL
);

CREATE TABLE "SO_DEP_HEAD_LOGIN_HISTORY" (
  "SO_DEP_HEAD_ID" INT NOT NULL,
  "LOGIN_TIME" TIMESTAMP NOT NULL,
  "LOGOUTTIME" TIMESTAMP,
  "IPADDRESS" integer,
  "DESC" VARCHAR
);

CREATE TABLE "SO_DEP_HEAD_AUTH" (
  "SO_DEP_HEAD_ID" integer UNIQUE,
  "AUTH_CODE" varchar(100),
  "AUTH_SALT" varchar(100),
  "ENCTYPE" integer NOT NULL,
  "ADDED_ON" TIMESTAMP NOT NULL
);

CREATE TABLE "SO_SUB_DEP_HEAD_USERS" (
  "CREATED_BY" integer,
  "SO_SUBDEP_ID" integer,
  "STATE_ID" integer,
  "CITY_ID" integer,
  "EMAIL_ID" varchar(30) UNIQUE,
  "ID" integer UNIQUE,
  "NAME" varchar(30),
  "EMPLOYEE_ID" integer NOT NULL,
  "PHONE_NO" integer(10),
  "ADDED_ON" TIMESTAMP NOT NULL,
  "UPDATED_ON" TIMESTAMP,
  "STATUS" integer,
  PRIMARY KEY ("SO_SUBDEP_ID", "STATE_ID", "CITY_ID", "EMAIL_ID")
);

CREATE TABLE "SO_SUB_DEP_HEAD_AUTH_HISTORY" (
  "SO_SUB_DEP_HEAD_ID" INT,
  "AUTH_CODE" varchar(100),
  "AUTH_SALT" varchar(100),
  "ENCTYPE" integer NOT NULL,
  "ADDED_ON" TIMESTAMP NOT NULL
);

CREATE TABLE "SO_SUB_DEP_HEAD_LOGIN_HISTORY" (
  "SO_SUB_DEP_HEAD_ID" INT NOT NULL,
  "LOGIN_TIME" TIMESTAMP NOT NULL,
  "LOGOUTTIME" TIMESTAMP,
  "IPADDRESS" integer,
  "DESC" VARCHAR
);

CREATE TABLE "SO_SUB_DEP_HEAD_AUTH" (
  "SO_SUB_DEP_HEAD_ID" integer UNIQUE,
  "AUTH_CODE" varchar(100),
  "AUTH_SALT" varchar(100),
  "ENCTYPE" integer NOT NULL,
  "ADDED_ON" TIMESTAMP NOT NULL
);

CREATE TABLE "SO_SUB_DEP_USER_ROLES" (
  "ID" integer PRIMARY KEY,
  "ROLE_NAME" VARCHAR(15) UNIQUE,
  "DESC" VARCHAR(100),
  "FIN_ENABLE" BOOLEAN
);

CREATE TABLE "SO_SUB_DEP_USERS" (
  "CREATED_BY" integer,
  "SO_SUBDEP_ID" integer,
  "ROLE_ID" integer,
  "STATE_ID" integer,
  "CITY_ID" integer,
  "EMAIL_ID" varchar(30) UNIQUE,
  "ID" integer UNIQUE,
  "NAME" varchar(30),
  "EMPLOYEE_ID" integer NOT NULL,
  "PHONE_NO" integer(10),
  "ADDED_ON" TIMESTAMP NOT NULL,
  "UPDATED_ON" TIMESTAMP,
  "STATUS" integer
);

CREATE TABLE "SO_SUB_DEP_USERS_AUTH_HISTORY" (
  "SO_SUB_DEP_USER_ID" INT,
  "AUTH_CODE" varchar(100),
  "AUTH_SALT" varchar(100),
  "ENCTYPE" integer NOT NULL,
  "ADDED_ON" TIMESTAMP NOT NULL
);

CREATE TABLE "SO_SUB_DEP_USERS_LOGIN_HISTORY" (
  "SO_SUB_DEP_USER_ID" INT NOT NULL,
  "LOGIN_TIME" TIMESTAMP NOT NULL,
  "LOGOUTTIME" TIMESTAMP,
  "IPADDRESS" integer,
  "DESC" VARCHAR
);

CREATE TABLE "SO_SUB_DEP_USERS_AUTH" (
  "SO_SUB_DEP_USER_ID" integer UNIQUE,
  "AUTH_CODE" varchar(100),
  "AUTH_SALT" varchar(100),
  "ENCTYPE" integer NOT NULL,
  "ADDED_ON" TIMESTAMP NOT NULL
);

CREATE INDEX ON "SO_SUB_DEP_HEAD_USERS" ("SO_SUBDEP_ID", "STATE_ID", "CITY_ID", "EMAIL_ID");

CREATE UNIQUE INDEX ON "SO_SUB_DEP_HEAD_USERS" ("ID");

CREATE INDEX ON "SO_SUB_DEP_USERS" ("SO_SUBDEP_ID", "STATE_ID", "CITY_ID", "EMAIL_ID");

CREATE UNIQUE INDEX ON "SO_SUB_DEP_USERS" ("ID");

ALTER TABLE "HO_ADMIN_USERS" ADD FOREIGN KEY ("CREATED_BY") REFERENCES "SYSTEM_USERS" ("ID");

ALTER TABLE "CITY" ADD FOREIGN KEY ("STATE_ID") REFERENCES "STATE" ("ID");

ALTER TABLE "SO_SUB_DEPARTMENTS" ADD FOREIGN KEY ("SO_DEP_ID") REFERENCES "SO_DEPARTMENTS" ("ID");

ALTER TABLE "SO_ADMIN_USERS" ADD FOREIGN KEY ("CREATED_BY") REFERENCES "HO_ADMIN_USERS" ("ID");

ALTER TABLE "SO_ADMIN_USERS" ADD FOREIGN KEY ("STATE_ID") REFERENCES "STATE" ("ID");

ALTER TABLE "SO_ADMIN_USERS" ADD FOREIGN KEY ("CITY_ID") REFERENCES "CITY" ("ID");

ALTER TABLE "SO_ADMIN_USERS" ADD FOREIGN KEY ("STATUS") REFERENCES "SO_USER_STATUS" ("ID");

ALTER TABLE "SO_ADMIN_AUTH_HISTORY" ADD FOREIGN KEY ("SO_ADMIN_ID") REFERENCES "SO_ADMIN_USERS" ("ID");

ALTER TABLE "SO_ADMIN_AUTH_HISTORY" ADD FOREIGN KEY ("ENCTYPE") REFERENCES "ENC_TYPES" ("ID");

ALTER TABLE "SO_ADMIN_LOGIN_HISTORY" ADD FOREIGN KEY ("SO_ADMIN_ID") REFERENCES "SO_ADMIN_USERS" ("ID");

ALTER TABLE "SO_ADMIN_AUTH" ADD FOREIGN KEY ("SO_ADMIN_ID") REFERENCES "SO_ADMIN_USERS" ("ID");

ALTER TABLE "SO_ADMIN_AUTH" ADD FOREIGN KEY ("ENCTYPE") REFERENCES "ENC_TYPES" ("ID");

ALTER TABLE "SO_DEP_HEAD_USERS" ADD FOREIGN KEY ("CREATED_BY") REFERENCES "SO_ADMIN_USERS" ("ID");

ALTER TABLE "SO_DEP_HEAD_USERS" ADD FOREIGN KEY ("SO_DEP_ID") REFERENCES "SO_DEPARTMENTS" ("ID");

ALTER TABLE "SO_DEP_HEAD_USERS" ADD FOREIGN KEY ("STATE_ID") REFERENCES "STATE" ("ID");

ALTER TABLE "SO_DEP_HEAD_USERS" ADD FOREIGN KEY ("CITY_ID") REFERENCES "CITY" ("ID");

ALTER TABLE "SO_DEP_HEAD_USERS" ADD FOREIGN KEY ("STATUS") REFERENCES "SO_USER_STATUS" ("ID");

ALTER TABLE "SO_DEP_HEAD_AUTH_HISTORY" ADD FOREIGN KEY ("SO_DEP_HEAD_ID") REFERENCES "SO_DEP_HEAD_USERS" ("ID");

ALTER TABLE "SO_DEP_HEAD_AUTH_HISTORY" ADD FOREIGN KEY ("ENCTYPE") REFERENCES "ENC_TYPES" ("ID");

ALTER TABLE "SO_DEP_HEAD_LOGIN_HISTORY" ADD FOREIGN KEY ("SO_DEP_HEAD_ID") REFERENCES "SO_DEP_HEAD_USERS" ("ID");

ALTER TABLE "SO_DEP_HEAD_AUTH" ADD FOREIGN KEY ("SO_DEP_HEAD_ID") REFERENCES "SO_DEP_HEAD_USERS" ("ID");

ALTER TABLE "SO_DEP_HEAD_AUTH" ADD FOREIGN KEY ("ENCTYPE") REFERENCES "ENC_TYPES" ("ID");

ALTER TABLE "SO_SUB_DEP_HEAD_USERS" ADD FOREIGN KEY ("CREATED_BY") REFERENCES "SO_DEP_HEAD_USERS" ("ID");

ALTER TABLE "SO_SUB_DEP_HEAD_USERS" ADD FOREIGN KEY ("SO_SUBDEP_ID") REFERENCES "SO_SUB_DEPARTMENTS" ("ID");

ALTER TABLE "SO_SUB_DEP_HEAD_USERS" ADD FOREIGN KEY ("STATE_ID") REFERENCES "STATE" ("ID");

ALTER TABLE "SO_SUB_DEP_HEAD_USERS" ADD FOREIGN KEY ("CITY_ID") REFERENCES "CITY" ("ID");

ALTER TABLE "SO_SUB_DEP_HEAD_USERS" ADD FOREIGN KEY ("STATUS") REFERENCES "SO_USER_STATUS" ("ID");

ALTER TABLE "SO_SUB_DEP_HEAD_AUTH_HISTORY" ADD FOREIGN KEY ("SO_SUB_DEP_HEAD_ID") REFERENCES "SO_SUB_DEP_HEAD_USERS" ("ID");

ALTER TABLE "SO_SUB_DEP_HEAD_AUTH_HISTORY" ADD FOREIGN KEY ("ENCTYPE") REFERENCES "ENC_TYPES" ("ID");

ALTER TABLE "SO_SUB_DEP_HEAD_LOGIN_HISTORY" ADD FOREIGN KEY ("SO_SUB_DEP_HEAD_ID") REFERENCES "SO_SUB_DEP_HEAD_USERS" ("ID");

ALTER TABLE "SO_SUB_DEP_HEAD_AUTH" ADD FOREIGN KEY ("SO_SUB_DEP_HEAD_ID") REFERENCES "SO_SUB_DEP_HEAD_USERS" ("ID");

ALTER TABLE "SO_SUB_DEP_HEAD_AUTH" ADD FOREIGN KEY ("ENCTYPE") REFERENCES "ENC_TYPES" ("ID");

ALTER TABLE "SO_SUB_DEP_USERS" ADD FOREIGN KEY ("CREATED_BY") REFERENCES "SO_SUB_DEP_HEAD_USERS" ("ID");

ALTER TABLE "SO_SUB_DEP_USERS" ADD FOREIGN KEY ("SO_SUBDEP_ID") REFERENCES "SO_SUB_DEPARTMENTS" ("ID");

ALTER TABLE "SO_SUB_DEP_USERS" ADD FOREIGN KEY ("ROLE_ID") REFERENCES "SO_SUB_DEP_USER_ROLES" ("ID");

ALTER TABLE "SO_SUB_DEP_USERS" ADD FOREIGN KEY ("STATE_ID") REFERENCES "STATE" ("ID");

ALTER TABLE "SO_SUB_DEP_USERS" ADD FOREIGN KEY ("CITY_ID") REFERENCES "CITY" ("ID");

ALTER TABLE "SO_SUB_DEP_USERS" ADD FOREIGN KEY ("STATUS") REFERENCES "SO_USER_STATUS" ("ID");

ALTER TABLE "SO_SUB_DEP_USERS_AUTH_HISTORY" ADD FOREIGN KEY ("SO_SUB_DEP_USER_ID") REFERENCES "SO_SUB_DEP_USERS" ("ID");

ALTER TABLE "SO_SUB_DEP_USERS_AUTH_HISTORY" ADD FOREIGN KEY ("ENCTYPE") REFERENCES "ENC_TYPES" ("ID");

ALTER TABLE "SO_SUB_DEP_USERS_LOGIN_HISTORY" ADD FOREIGN KEY ("SO_SUB_DEP_USER_ID") REFERENCES "SO_SUB_DEP_USERS" ("ID");

ALTER TABLE "SO_SUB_DEP_USERS_AUTH" ADD FOREIGN KEY ("SO_SUB_DEP_USER_ID") REFERENCES "SO_SUB_DEP_USERS" ("ID");

ALTER TABLE "SO_SUB_DEP_USERS_AUTH" ADD FOREIGN KEY ("ENCTYPE") REFERENCES "ENC_TYPES" ("ID");
